name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run Jest tests
      run: npm test -- --coverage --coverageReporters=cobertura

    - name: Prepare SonarQube properties
      run: |
        echo "sonar.projectKey=$SONAR_PROJECT_KEY" > sonar-project.properties
        echo "sonar.organization=$SONAR_ORGANIZATION" >> sonar-project.properties
        echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
        echo "sonar.login=$SONAR_TOKEN" >> sonar-project.properties
        echo "sonar.javascript.lcov.reportPaths=coverage/lcov.info" >> sonar-project.properties

    - name: Run SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
